# Generated by Django 4.1.7 on 2023-03-24 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_id', models.CharField(max_length=128)),
                ('date', models.CharField(max_length=128)),
                ('text', models.TextField(max_length=4096)),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.chats')),
            ],
        ),
    ]
